In [1]:
# Scenario 1: Online Course Completion Prediction
# We want to classify whether a student will complete an online course (1) or drop out (0) based on two features:

# Videos Watched – number of course videos the student watched

# Time Spent on Platform – total minutes spent on the learning platform

# Students who watch more videos and spend more time learning are more likely to complete the course.

In [4]:
import numpy as np

X = np.array([[2,15],
              [3,20],
              [8,60],
              [9,75]])

y = np.array([[0],[0],[1],[1]])

In [5]:
np.random.seed(42)
weights_input_hidden = np.random.rand(2,2)
bias_hidden = np.random.rand(1,2)
weights_hidden_output = np.random.rand(2,1)
bias_output = np.random.rand(1,1)
learning_rate = 0.1

In [7]:
print(weights_input_hidden)
print(bias_hidden)
print(weights_hidden_output)
print(bias_output)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
[[0.15601864 0.15599452]]
[[0.05808361]
 [0.86617615]]
[[0.60111501]]


In [8]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def sigmoid_derivative(z):
    return z*(1-z)

In [9]:
for epoch in range(1000):
    hidden_input = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    final_output = sigmoid(final_input)

    error = y - final_output

    d_output = error * sigmoid_derivative(final_output)

    error_hidden = np.dot(d_output, weights_hidden_output.T)

    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    weights_hidden_output += np.dot(hidden_output.T, d_output) * learning_rate
    bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    weights_input_hidden += np.dot(X.T, d_hidden) * learning_rate
    bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate



In [10]:
test_data = np.array([[5,50],   
                      [1,10]])  

hidden_test = sigmoid(np.dot(test_data, weights_input_hidden) + bias_hidden)
final_test = sigmoid(np.dot(hidden_test, weights_hidden_output) + bias_output)

print("Predictions:", final_test)

Predictions: [[0.50000116]
 [0.49996962]]
